version: "2"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: bendbennett/php7-fpm:v0.4.0

  mongo:
    image: mongo:latest
