version: "2"

services:
  nginx:
    image: bendbennett/nginx:1.17
    ports:
      - "80:80"
    # volumes:
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: bendbennett/php7-fpm:7.3

  mongo:
    image: bendbennett/mongo-seeded:4.0
